cmake_minimum_required(VERSION 3.20)

set(SOURCE_TEST_PATH "${KRB_SOURCE_DIR}/${KRB_TEST_SOURCE_FILENAME}.in")
set(BUILD_SOURCE_TEST_PATH "${KRB_BUILD_PATH}/${KRB_TEST_SOURCE_FILENAME}")
configure_file(${SOURCE_TEST_PATH} ${BUILD_SOURCE_TEST_PATH})